name: Metrics

on:
  schedule:
    - cron: "0 * * * *" # Every hour
  workflow_dispatch: # Allows manual trigger

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics.svg
          base: header, repositories
